// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriFood.Infrastructure.Persistence.Context;

#nullable disable

namespace NutriFood.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NutriFoodDbContext))]
    [Migration("20260923194903_AddRecipeFoodAttributeValues")]
    partial class AddRecipeFoodAttributeValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutriFood.Domain.Entities.AdequacyAttributeValue", b =>
                {
                    b.Property<int>("AdequacyPercentageId")
                        .HasColumnType("integer")
                        .HasColumnName("adequacy_percentage_id");

                    b.Property<short>("AttributeId")
                        .HasColumnType("smallint")
                        .HasColumnName("attribute_id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("crea_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("CreaUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("crea_usr");

                    b.Property<DateTime>("ModDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mod_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ModUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("mod_usr");

                    b.Property<double>("Percentage")
                        .HasColumnType("float")
                        .HasColumnName("percentage");

                    b.HasKey("AdequacyPercentageId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("adequacy_attribute_values", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.AdequacyPercentage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("crea_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("CreaUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("crea_usr");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("ModDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mod_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ModUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("mod_usr");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("adequacy_percentage", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("crea_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("CreaUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("crea_usr");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short>("FoodCategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("food_category_id");

                    b.Property<short>("FoodClassificationId")
                        .HasColumnType("smallint")
                        .HasColumnName("food_classification_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<DateTime>("ModDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mod_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ModUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("mod_usr");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("FoodCategoryId");

                    b.HasIndex("FoodClassificationId");

                    b.ToTable("foods", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodAttribute", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short>("MeasureUnitId")
                        .HasColumnType("smallint")
                        .HasColumnName("measure_unit_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MeasureUnitId");

                    b.ToTable("food_attributes", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodAttributeValue", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("integer")
                        .HasColumnName("food_id");

                    b.Property<short>("AttributeId")
                        .HasColumnType("smallint")
                        .HasColumnName("attribute_id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("crea_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("CreaUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("crea_usr");

                    b.Property<DateTime>("ModDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mod_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ModUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("mod_usr");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("FoodId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("food_attribute_values", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodCategory", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("food_categories", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodClassification", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("food_classifications", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("crea_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("CreaUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("crea_usr");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("meal_plan_id");

                    b.Property<short?>("MealTimeId")
                        .HasColumnType("smallint")
                        .HasColumnName("meal_time_id");

                    b.Property<DateTime>("ModDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mod_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ModUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("mod_usr");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("MealTimeId");

                    b.ToTable("food_menus", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<int>("AdequacyPercentageId")
                        .HasColumnType("integer")
                        .HasColumnName("adequacy_percentage_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("crea_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("CreaUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("crea_usr");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("ModDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mod_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ModUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("mod_usr");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AdequacyPercentageId");

                    b.ToTable("meal_plans", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.MealTime", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("meal_times", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.MeasureUnit", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("abbreviation");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("measure_units", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.Menu", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("crea_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("CreaUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("crea_usr");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("IdCard")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("id_card");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("ModDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mod_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ModUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("mod_usr");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreaDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("CreaUsr")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FoodMenuId")
                        .HasColumnType("integer")
                        .HasColumnName("food_menu_id");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("ModUsr")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("FoodMenuId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.RecipeFood", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer")
                        .HasColumnName("food_id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("crea_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("CreaUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("crea_usr");

                    b.Property<short>("MeasureUnitId")
                        .HasColumnType("smallint")
                        .HasColumnName("measure_unit_id");

                    b.Property<DateTime>("ModDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mod_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ModUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("mod_usr");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.HasKey("RecipeId", "FoodId");

                    b.HasIndex("FoodId");

                    b.HasIndex("MeasureUnitId");

                    b.ToTable("recipe_foods", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.RecipeFoodAttributeValue", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer")
                        .HasColumnName("food_id");

                    b.Property<short>("AttributeId")
                        .HasColumnType("smallint")
                        .HasColumnName("attribute_id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("crea_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("CreaUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("crea_usr");

                    b.Property<DateTime>("ModDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mod_date")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ModUsr")
                        .HasColumnType("smallint")
                        .HasColumnName("mod_usr");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("RecipeId", "FoodId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("recipe_food_attribute_values", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.User", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreaDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("crea_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mod_date");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.AdequacyAttributeValue", b =>
                {
                    b.HasOne("NutriFood.Domain.Entities.AdequacyPercentage", "AdequacyPercentage")
                        .WithMany("AdequacyAttributeValues")
                        .HasForeignKey("AdequacyPercentageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriFood.Domain.Entities.FoodAttribute", "Attribute")
                        .WithMany("AdequacyAttributeValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdequacyPercentage");

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.AdequacyPercentage", b =>
                {
                    b.HasOne("NutriFood.Domain.Entities.Patient", "Patient")
                        .WithMany("AdequacyPercentages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.Food", b =>
                {
                    b.HasOne("NutriFood.Domain.Entities.FoodCategory", "FoodCategory")
                        .WithMany("Foods")
                        .HasForeignKey("FoodCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriFood.Domain.Entities.FoodClassification", "FoodClassification")
                        .WithMany("Foods")
                        .HasForeignKey("FoodClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodCategory");

                    b.Navigation("FoodClassification");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodAttribute", b =>
                {
                    b.HasOne("NutriFood.Domain.Entities.MeasureUnit", "MeasureUnit")
                        .WithMany("FoodAttributes")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasureUnit");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodAttributeValue", b =>
                {
                    b.HasOne("NutriFood.Domain.Entities.FoodAttribute", "Attribute")
                        .WithMany("FoodAttributeValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriFood.Domain.Entities.Food", "Food")
                        .WithMany("FoodAttributeValues")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodMenu", b =>
                {
                    b.HasOne("NutriFood.Domain.Entities.MealPlan", "MealPlan")
                        .WithMany("FoodMenus")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriFood.Domain.Entities.MealTime", "MealTime")
                        .WithMany("FoodMenus")
                        .HasForeignKey("MealTimeId");

                    b.Navigation("MealPlan");

                    b.Navigation("MealTime");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.MealPlan", b =>
                {
                    b.HasOne("NutriFood.Domain.Entities.AdequacyPercentage", "AdequacyPercentage")
                        .WithMany("MealPlans")
                        .HasForeignKey("AdequacyPercentageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdequacyPercentage");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.Patient", b =>
                {
                    b.HasOne("NutriFood.Domain.Entities.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("NutriFood.Domain.Entities.FoodMenu", "FoodMenu")
                        .WithMany("Recipes")
                        .HasForeignKey("FoodMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodMenu");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.RecipeFood", b =>
                {
                    b.HasOne("NutriFood.Domain.Entities.Food", "Food")
                        .WithMany("RecipeFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriFood.Domain.Entities.MeasureUnit", "MeasureUnit")
                        .WithMany("RecipeFoods")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriFood.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeFoods")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("MeasureUnit");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.RecipeFoodAttributeValue", b =>
                {
                    b.HasOne("NutriFood.Domain.Entities.FoodAttribute", "Attribute")
                        .WithMany("RecipeFoodAttributeValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriFood.Domain.Entities.RecipeFood", "RecipeFood")
                        .WithMany("RecipeFoodAttributeValues")
                        .HasForeignKey("RecipeId", "FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("RecipeFood");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.AdequacyPercentage", b =>
                {
                    b.Navigation("AdequacyAttributeValues");

                    b.Navigation("MealPlans");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.Food", b =>
                {
                    b.Navigation("FoodAttributeValues");

                    b.Navigation("RecipeFoods");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodAttribute", b =>
                {
                    b.Navigation("AdequacyAttributeValues");

                    b.Navigation("FoodAttributeValues");

                    b.Navigation("RecipeFoodAttributeValues");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodClassification", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.FoodMenu", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.MealPlan", b =>
                {
                    b.Navigation("FoodMenus");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.MealTime", b =>
                {
                    b.Navigation("FoodMenus");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.MeasureUnit", b =>
                {
                    b.Navigation("FoodAttributes");

                    b.Navigation("RecipeFoods");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.Patient", b =>
                {
                    b.Navigation("AdequacyPercentages");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeFoods");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.RecipeFood", b =>
                {
                    b.Navigation("RecipeFoodAttributeValues");
                });

            modelBuilder.Entity("NutriFood.Domain.Entities.User", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
